export const GET_FRAGNANCE_DATA_SUCCESS = "GET_FRAGNANCE_DATA_SUCCESS";
export const GET_FRAGNANCE_DATA_FAILED = "GET_FRAGNANCE_DATA_FAILED";
export const GET_FRAGNANCE_DATA_REQUEST = "GET_FRAGNANCE_DATA_REQUEST";
